### ISSUE TITLE
Implement User Locations

### ISSUE THREAD

**Issue by FoRVaiS** [Geek-Collectors-Network/geek-collectors-network#160]
### Description
Our data models need to include locations for systems like #88 (including various future features) to be able to filter users by location.

The location data we should prompt users for include:
 - Country
 - Province
 - City

#### Frontend
 - [x] Add location fields to "Sign Up" and "Edit Profile" pages
 - [x] Update requests to include location data (Blocked by #149)

#### Backend
 - [x] Add location columns to user schema
 - [x] Handle location data in sign-up and profile-patch routes

&nbsp;
This task can be implemented in a single PR.

**Comment by tgrigoruk** [comment]
I don't think the user needs to enter their location during sign up.

I think we can validate the location given by passing the user's input to a geocoding service (e.g. https://positionstack.com/). The response should contain a properly formed (and spelled) location that can be presented for the user to select, for example.

Province should be called "Region", and the frontend will determine if it should display field as State, Province, Territory etc depending on the Country chosen. Thus it should ask for Country first (and ideally only then reveal the Region field).
