### ISSUE TITLE
Create an issue and pull request template

### ISSUE THREAD

**Issue by FoRVaiS** [Geek-Collectors-Network/geek-collectors-network#50]
### Proposal
We should have templates for issues and pull request to streamline the creation and submission of tasks.

### Solution
Create markdown templates in `.github/` for issues and pull requests.

Feature requests/Changes should have a section for:
 - Description - What needs to be add or changed?
 - Solution - What needs to be done to complete this task?

Bug reports should have a section for:
 - Bug Description - A description of what the problem is
 - Expected Behaviour
 - Actual Behaviour
 - System Info
 - Steps to Reproduce

Pull Requests should contains sections for:
 - Summary - A description of the changes made
 - Retrospective - Anything to share for others to benefit from
 - Reviewer's Notes - Anything the reviewers need to know before testing
 - Testing - Instructions for reviews to test changes

**Comment by tgrigoruk** [comment]
These look great. I would also like to recommend we use short bullet points etc. where possible.
