### ISSUE TITLE
Create "User Profile Card" UI Component

### ISSUE THREAD

**Issue by tgrigoruk** [Geek-Collectors-Network/geek-collectors-network#90]
### Summary

UserCard is used in lists of users in various places with different buttons depending on context:
- friend requests: approve, deny
- recommended users: connect, hide
- friend list: social media buttons

### Requirements

- [ ] Create a `UserProfileCard` component that accepts dynamically populated props; the props will contain user information from the database
- [ ] Create a `UserProfileCardContainer`, which uses `useEffect` to fetch data from the database and `useState` to display that data

---

![Image](https://github.com/Geek-Collectors-Network/geek-collectors-network/assets/97200544/c95c4de7-b680-43ed-9118-8e4950f6ef2f)

**Comment by FoRVaiS** [comment]
Can't reference it in the side-panel, it's bugged lol. Tracking for ease of access.

PR: #111
